### ISSUE TITLE
Stability and project status

### ISSUE THREAD

**Issue by capacman** [adejanovski/cassandra-dcaware-failover#1]
Hi ,

I came across this project when i try to find a similar solution for our failover requirement. Is this project battle tested? I mean did anyone had/have used it in production? Also is it abandoned since latest commit is more than one year ago or this means that is is already Rock solid.

Thanks in advance

**Comment by fosholaw** [comment]
+1 on the question.

**Comment by sbilello** [comment]
+1 on the question @adejanovski

**Comment by adejanovski** [comment]
This project has been used (and probably still is) in production at my former company.
It is not actively maintained and I do not know how it works with recent versions of the java driver (it is probably not working with 4.x versions of the driver as a lot of things have been changed there).
